name: Montlaur.net
author: "Famille de Montlaur"
url: https://montlaur.net

# Where things are
source:          .
destination:     ./_site
collections_dir: null
plugins_dir:     _plugins
layouts_dir:     _layouts
data_dir:        _data
includes_dir:    _includes
collections:
  posts:
    output:   true

plugins:
  - jekyll-paginate-v2
  - jekyll-feed

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/blog/page:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Blog permalink
permalink: /blog/:categories/:year/:month/:day/:title:output_ext

# Handling Reading
safe:                false
include:             [".htaccess"]
exclude:             ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:          [".git", ".svn"]
encoding:            "utf-8"
markdown_ext:        "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
  parse_block_html: true
